### ISSUE TITLE
Spring Boot Admin can't find other new services

### ISSUE THREAD

**Issue by zhangbinhub** [alibaba/spring-cloud-alibaba#3260]
Environment:
Spring Boot 3.0.5
Spring Cloud 2022.0.2
Spring Cloud Alibaba 2022.0.0.0-RC1
Nacos 2.2.1

Spring Boot Admin 3.0.2

Start SBA first, and then start other services, but the web page always shows a service (SBA)
首先启动 spring boot admin，然后再启动其他服务，这时spring boot admin的界面发现不了其他服务。
假如先启动其他服务，再启动spring boot admin，这时spring boot admin的界面就可以展示其他服务。

**Comment by yuluo-yx** [comment]
Perhaps you can ask this question to the [Sping Boot Admin community](https://github.com/codecentric/spring-boot-admin/issues)

**Comment by steverao** [comment]
This is a problem about Spring Boot Admin, you need to relevant community ask for help.

**Comment by zhangbinhub** [comment]
@steverao I have already posted issu on the sba community, but they have labeled it as nacos
https://github.com/codecentric/spring-boot-admin/issues/2390

**Comment by CrushDope** [comment]
I also encountered the same problem, is your problem solved now?

**Comment by zhangbinhub** [comment]
> I also encountered the same problem, is your problem solved now?

Not resolved yet...
I have raised issues here and in the Sping Boot Admin community, but there is no clear response

**Comment by CrushDope** [comment]
> > I also encountered the same problem, is your problem solved now?
> 
> Not resolved yet... I have raised issues here and in the Sping Boot Admin community, but there is no clear response [但没有明确回应]

yep，I read all the issues in the Spring Boot Admin community and came there.And then please let me know if there is a solution to this problem

**Comment by zhangbinhub** [comment]
> > > I also encountered the same problem, is your problem solved now?
> > 
> > 
> > Not resolved yet... I have raised issues here and in the Sping Boot Admin community, but there is no clear response [但没有明确回应]
> 
> yep，I read all the issues in the Spring Boot Admin community and came there.And then please let me know if there is a solution to this problem

I think it's still a [issue](https://github.com/codecentric/spring-boot-admin/issues/2390) in sba, but they have labeled it as nacos...
